
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: alpine:latest
pages:
  stage: deploy
  script:
  - echo "doing nothing"
  artifacts:
    paths:
    - public
  only:
  - master
