sequenceDiagram
    participant ui as User Interactions
    participant sn as Servicenow
    participant ms as MidServer
    participant co as Certificate Authority
    ui->>sn: User Requests Cert
    sn->>ms: Run generate-csr-key.js
    ms->>co: CSR,KEY, and Enrolls Cert
    co->>sn: Returns Order #
loop Download
    sn->>sn: Waits 2 minutes
    sn->>ms: Run download-zip-and-upload-cert.js
    ms->>co: Download Cert
    co->>sn: Cert Processing
end
    co->>ms: Cert Downloaded
    ms->>ms: Generate CRT
    ms->>ms: Generate PFX
    ms->>ms: Zip CRT, PFX, P7B
    ms->>sn: Send Zip to SN
    sn->>ui: Notify user with zip file
