graph TD
  Start[Start]
  Task1[Task 1]
  Task2[Task 2]
  System1[System 1]
  System2[System 2]
  End[End]

  Start[Start] --> Task1
  Start[Start] --> Task2
  Task1-->Join
  Task2-->Join
  Join-->End
  subgraph SN Outbound Task Automation
    Task1--API Call-->System1
    System1--Does work to automate work-->System1
    System1--API Call to Close and Comment-->Task1
  end
  
  subgraph SN Inbound Task Automation
    System2--On a schedule polls for tasks from SN-->System2
    System2--API Call for Tasks Closes Task when complete-->Task2
  end
