graph TD
  SN3[Weeky ServiceNow asks <Br/>for each Account and<br/> each datacenter for resources]

  L0[Loop over each resource]
  P0[Process responses<br/>sometimes this contains<br/>terminate but only for<br/> less than an hour]
  SN3 --rest call to AWS-->L0
  L0 --> P0
  P0 --Create--> C0[Create CIs]
  P0 --Update--> U0
  SNS0[AWS SNS]
  SNS0--Create-->SN0[ServiceNow]
  SN0-->C0
  SNS0--Update-->SN1[ServiceNow]
  SN1-->U0[Update CI]
  SNS0--Delete-->SN2[ServiceNow]
  SN2-->D0[Terminate CI]
subgraph CUSTOM
  SN4[Daily Servicenow looks<br/> for records with sys_updated<br/>older than 14 days]
end
  SN4--Change state to retired-->D0
