graph TD
  Start[Start] --> Approval[Manager Approval]
  Approval--Approved--> Task[Fulfiller Task]
  Task-->End
  Approval--Rejected--> End
  subgraph Manager Approval
    MAEmail[Email to Manager]-->MAApproved[Approved]
    MAEmail-->MARejected[Rejected]
    MAEmail-->MAWait[Wait 7 days]
    MAWait-->MAEmail
  end
  subgraph Fulfiller Task
    FTAssigned[Task Assigned to Group]-->FTEmailGroup[Email To Group]
    FTEmailGroup-->TaskComplete[Task Complete]
  end
