graph TB
  subgraph New
    NEW(State: New)
    A+D(State: Analysis + Design)
  end
  subgraph Backlog
    BAC(State: Backlog)
  end
  subgraph In Progress
    DEV(State: Development + Testing)  
    REQ(Approval: Requested)
    PRO(State: Production Change)
    DEP(State: Deploy)
  end
  subgraph Closed
    COM(State: Closed Complete)
  end
  CIN(State: Closed Incomplete)

  NEW--Removed-->CIN
  NEW--Requirements Clear: No-->A+D
  NEW--Requirements Clear: Yes-->BAC
  A+D--Removed-->CIN
  A+D-->BAC
  BAC-->DEV
  DEV--Work done-->REQ
  REQ--Approved-->PRO
  REQ--Rejected-->DEV
  PRO--Moved to other environments-->DEP
  DEP--Promoted-->COM

