graph TD

  SN1(ServiceNow)
  SN2(ServiceNow)
  SN3(ServiceNow)
  SN4(ServiceNow)
  OS1(Other System)
  OS2(Other System)
  OS4(Other System)
  TM1(Transform Map)
  TM2(Transform Map)
  TM4(Transform Map)
  EN1(End)
  EN2(End)
  EN3(End)
  EN4(End)

  subgraph One record at a time SN Pulls
    SN1--Asks for data-->OS1
    OS1--Replies-->SN1
    SN1--Inserts one record at time to process on the import set row level-->TM1
    TM1--Creates Records-->EN1
  end
  subgraph One record at a time Other System Pushs
    OS2--Sends data in to Import Set API-->SN2
    SN2--Inserts one record at time to process on the import set row level-->TM2
    TM2--Creates Records-->EN2
  end
  subgraph Many records at a time SN Pulls
    SN3--Dont do it-->EN3
  end
  subgraph Many records at a time OS Pushes
    OS4--Sends many records in to Scripted Rest API-->SN4
    SN4--Inserts one record at time to process on the import set row level-->TM4
    TM4--Creates Records-->EN4
  end
