graph LR
  S0[Start]
  T0[Timer]
  I1[If Ergonomic Split]
  I2[If Ergonomic]
  I3[If Gaming]
  I4[If Standard]
  T1[Task 1]
  T2[Task 2]
  T3[Task 3]
  T4[Task 4]
  B1[Branch 1]
  B2[Branch 2]
  B3[Branch 3]
  B4[Branch 4]
  J0[Join]
  R0[Run Script]
  E0[End]
  
  S0-->T0
  T0-->I1
  T0-->I2
  T0-->I3
  T0-->I4
  I1--No-->B1
  I2--No-->B2
  I3--No-->B3
  I4--No-->B4
  I1--Yes-->T1
  I2--Yes-->T2
  I3--Yes-->T3
  I4--Yes-->T4
  T1-->B1
  T2-->B2
  T3-->B3
  T4-->B4
  B1-->J0
  B2-->J0
  B3-->J0
  B4-->J0
  J0-->R0
  R0-->E0